joints: {
    joint_1: {id: 1, max_angle: 170, min_angle: -170, max_speed: 90},
    joint_2: {id: 2, max_angle: 120, min_angle: -120, max_speed: 90},
    joint_3: {id: 3, max_angle: 120, min_angle: -120, max_speed: 90},
    joint_4: {id: 4, max_angle: 170, min_angle: -170, max_speed: 90},
    joint_5: {id: 5, max_angle: 120, min_angle: -120, max_speed: 90},
    joint_6: {id: 6, max_angle: 175, min_angle: -175, max_speed: 90},
}
controllers: {
    arm_controller: {type: follow_controller, joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6], action_name: arm_controller/follow_joint_trajectory, onboard: False }
}
